version: 0.2
phases:
  build:
    commands:
      - echo "Zipping up function"
      - zip function.zip mobileapp_salTest
  post_build:
    commands:
      - echo "Updating Lambda"
      - aws lambda update-function-code --function-name mobileapp_salTest --zip-file fileb://function.zip
      - echo "DONE!"