version: 0.2
phases:
  build:
    commands:
      - echo "Zipping up function"
      - cd mobileapp_salTest && zip -r ../salTest.zip ./*
      - cd ../mobileapp_getDashboardInfo && zip -r ../getDashboardInfo.zip ./*
  post_build:
    commands:
      - cd ..
      - echo "Updating Lambda"
      - aws lambda update-function-code --function-name mobileapp_salTest --zip-file fileb://salTest.zip
      - sleep 2
      # - aws lambda publish-version --function-name mobileapp_salTest --description 'Testing from codebuild' >> salTestOutput.json
      # - sleep 2
      # - cat salTestOutput.json
      # - salTestVersion=$(jq '.Version | tonumber' salTestOutput.json)
      # - aws lambda update-alias --function-name mobileapp_salTest --name QA --function-version ${salTestVersion}
      - aws lambda update-function-code --function-name mobileapp_getDashboardInfo --zip-file fileb://getDashboardInfo.zip
      - echo "DONE!"